/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicSignupRouteImport } from './routes/(public)/signup'
import { Route as ProtectedAuthRouteImport } from './routes/protected/_auth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignupRoute = publicSignupRouteImport.update({
  id: '/(public)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAuthRoute = ProtectedAuthRouteImport.update({
  id: '/protected/_auth',
  path: '/protected',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/signup': typeof publicSignupRoute
  '/protected': typeof ProtectedAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/signup': typeof publicSignupRoute
  '/protected': typeof ProtectedAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/signup': typeof publicSignupRoute
  '/protected/_auth': typeof ProtectedAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/protected'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/protected'
  id:
    | '__root__'
    | '/'
    | '/(public)/login'
    | '/(public)/signup'
    | '/protected/_auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  publicLoginRoute: typeof publicLoginRoute
  publicSignupRoute: typeof publicSignupRoute
  ProtectedAuthRoute: typeof ProtectedAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protected/_auth': {
      id: '/protected/_auth'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  publicLoginRoute: publicLoginRoute,
  publicSignupRoute: publicSignupRoute,
  ProtectedAuthRoute: ProtectedAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
